CREATE DATABASE K22CNT1_lexuantoan_Project3
go
use K22CNT1_lexuantoan_Project3
go

CREATE TABLE NGUOIDUNG (
    MaNguoiDung INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    TaiKhoan NVARCHAR(50) UNIQUE NOT NULL,
    MatKhau NVARCHAR(255) NOT NULL,
    LoaiNguoiDung NVARCHAR(50) CHECK (LoaiNguoiDung IN ('Admin', 'BacSi', 'NhanVien', 'BenhNhan')),
    SoDienThoai NVARCHAR(15) UNIQUE,
    Email NVARCHAR(100) UNIQUE,
    DiaChi NVARCHAR(255),
    NgayTao DATETIME DEFAULT GETDATE()
);

CREATE TABLE BENHNHAN (
    MaBenhNhan INT IDENTITY(1,1) PRIMARY KEY,
    MaNguoiDung INT FOREIGN KEY REFERENCES NGUOIDUNG(MaNguoiDung) ON DELETE CASCADE,
    NgaySinh DATE,
    GioiTinh NVARCHAR(10) CHECK (GioiTinh IN ('Nam', 'Nữ', 'Khác')),
    SoCMND NVARCHAR(15) UNIQUE,
    BaoHiemYTe NVARCHAR(20),
    GhiChu NVARCHAR(255)
);

CREATE TABLE BACSI (
    MaBacSi INT IDENTITY(1,1) PRIMARY KEY,
    MaNguoiDung INT FOREIGN KEY REFERENCES NGUOIDUNG(MaNguoiDung) ON DELETE CASCADE,
    ChuyenKhoa NVARCHAR(100),
    KinhNghiem INT,
    TrinhDo NVARCHAR(100),
    GhiChu NVARCHAR(255)
);

CREATE TABLE DICHVU (
    MaDichVu INT IDENTITY(1,1) PRIMARY KEY,
    TenDichVu NVARCHAR(255) NOT NULL,
    MoTa NVARCHAR(500),
    GiaTien DECIMAL(18,2) NOT NULL CHECK (GiaTien >= 0)
);

CREATE TABLE HOADON (
    MaHoaDon INT IDENTITY(1,1) PRIMARY KEY,
    MaBenhNhan INT FOREIGN KEY REFERENCES BENHNHAN(MaBenhNhan) ON DELETE CASCADE,
    NgayLap DATETIME DEFAULT GETDATE(),
    TongTien DECIMAL(18,2) DEFAULT 0 CHECK (TongTien >= 0),
    TrangThai NVARCHAR(50) CHECK (TrangThai IN ('Chưa Thanh Toán', 'Đã Thanh Toán'))
);
CREATE TABLE CHITIETHOADON (
    MaChiTiet INT IDENTITY(1,1) PRIMARY KEY,
    MaHoaDon INT FOREIGN KEY REFERENCES HOADON(MaHoaDon) ON DELETE CASCADE,
    MaDichVu INT FOREIGN KEY REFERENCES DICHVU(MaDichVu) ON DELETE CASCADE,
    SoLuong INT CHECK (SoLuong > 0),
    ThanhTien DECIMAL(18,2) CHECK (ThanhTien >= 0)
);
CREATE TABLE BAOHIEM (
    MaBaoHiem INT IDENTITY(1,1) PRIMARY KEY,
    MaBenhNhan INT FOREIGN KEY REFERENCES BENHNHAN(MaBenhNhan) ON DELETE CASCADE,
    SoThe NVARCHAR(50) UNIQUE NOT NULL,
    LoaiBaoHiem NVARCHAR(50),
    HanSuDung DATE,
    TyLeHoTro DECIMAL(5,2) CHECK (TyLeHoTro BETWEEN 0 AND 100)
);
